//REGISTER
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

//LOGIN
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";

//LOGOUT
export const LOGOUT = "LOGOUT";

//MESSAGE
export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

//COMMENT
export const COMMENT_SUCCESS = "COMMENT_SUCCESS"
export const COMMENT_FAIL = "COMMENT_FAIL"
